#!/bin/csh -f

echo Generating petit regression test...

foreach t (*.t)
  set b = `basename $t .t`
  echo generating $t dependence differences:
  ../obj/petit -R$b.dep_diffs $t
  echo generating $t dependence relations:
  ../obj/petit -b -R$b.dep_rels $t
end
